language: node_js
node_js:
  - node
before_install:
  - yarn global add @vue/cli
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  "on":
    branch: master
  committer-from-gh: true
  github-token: $GITHUB_TOKEN