language: node_js
node_js:
  - node
before_install:
  - yarn global add @vue/cli
  - yarn
script:
  - yarn run build
delpoy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: dist
  on:
    branch: master
  committer-from-gh: true